name: First Workflow

on:
  workflow_dispatch:

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'ref/*/main')
    steps:
      - name: Branch Name
        run: |
          echo "Message from the first workflow: ${{ github.ref }}"
