name: First Workflow

on:
  workflow_dispatch:

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    if: github.ref == 'ref/heads/main'
    steps:
      - name: Branch Name
        run: |
          echo "Branch Name: ${{ github.ref }}"
