name: First Workflow

on:
  workflow_dispatch:

env:
  NAME: "Hello, GitHub Actions!"
  
jobs:
  if-condition:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}  # If condition
    steps:
      - name: Run task for main branch
        run: |
          echo "Running task for the main branch"
          echo "Original String: $NAME"
          
          # Replace 'GitHub' with 'World'
          new_string="${NAME//GitHub/World}"
          echo "Updated String: $new_string"

  else-condition:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}  # Else condition
    steps:
      - name: Run task for non-main branch
        run: |
          echo "Running task for non-main branch"
      
