name: First Workflow

on:
  workflow_dispatch:

env:
  NAME: "4.77.98"
  
jobs:
  if-condition:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}  # If condition
    steps:
      - name: Run task for main branch
        run: |
          echo "Running task for the main branch"
          echo "Original String: $NAME"
          
          # Replace 'GitHub' with 'World'
          new_string="${NAME//98/}"
          echo "Updated String: $new_string"
          if [ "${NAME" != *$new_string* ]; then
            echo "Success: $NAME, $new_string"
          else
            echo "Failed: $NAME, $new_string"
          fi
          
  else-condition:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}  # Else condition
    steps:
      - name: Run task for non-main branch
        run: |
          echo "Running task for non-main branch"
      
