name: First Workflow

on:
  workflow_dispatch:

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Name
        run: |
          echo "Message from the first workflow: ${{ github.ref }}"
