name: First Workflow

on:
  workflow_dispatch:

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Name
        run: |
          if [[ github.ref == 'ref/heads/main' ]]; then
            echo "If Part Executed Branch Name: ${{ github.ref }}"
          else 
            echo "Else Part Executed"

      
