name: Fourth Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release VersionNo'
        required: true
env:
  PILOT_BRANCH_NAME: ${{ 'refs/heads/release/' }}${{ inputs.release_version }}${{ '-common-pilot' }}
  
jobs:
  if-condition:
    runs-on: ubuntu-latest
    if: ${{ github.ref == env.PILOT_BRANCH_NAME }}
    steps:
      - name: Run task for main branch
        run: |
          echo "Running task for the  main branch"
          echo $GITHUB_REF
          echo ${{ env.PILOT_BRANCH_NAME }}
          echo $PILOT_BRANCH_NAME

  else-condition:
    runs-on: ubuntu-latest
    steps:
      - name: Run task for non-main branch
        run: |
          echo "Running task for $PILOT_BRANCH_NAME branch"
