name: Fourth Workflow Test

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release VersionNo'
        required: true
env:
  PILOT_BRANCH_NAME: "refs/heads/${{ inputs.release_version }}"

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Details
        run: |
          echo "Condition is true!"
          echo "${{ inputs.release_version }}"
          echo "${{ env.PILOT_BRANCH_NAME }}"
        
      - name: Run if condition is true
        run: |
          selected_branch_name="${{ github.ref }}"
          input_branch_name="${{ inputs.release_version }}"
          echo "$selected_branch_name"
          echo "$input_branch_name"
          echo "${{ input_branch_name }}"
          if [[ $selected_branch_name =~ $PILOT_BRANCH_NAME ]]; then
            echo "Running on main branch!"
          else
            echo "Running on other branch!"
          fi
