name: Fourth Main Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release VersionNo'
        required: true
  
jobs:
  if-condition:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, inputs.release_version) }}
    steps:
      - name: Run task for main branch
        run: |
          echo "Running task for the main branch"
          echo $GITHUB_REF
          echo ${{ inputs.release_version }}
          echo contains(github.ref, ${{ inputs.release_version }})

  else-condition:
    runs-on: ubuntu-latest
    steps:
      - name: Run task for non-main branch
        run: |
          echo "Running task for $PILOT_BRANCH_NAME branch"
