name: Fourth Workflow Test

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release VersionNo'
        required: true
env:
  PILOT_BRANCH_NAME: ${{ 'refs/heads/' }}${{ inputs.release_version }}

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run if condition is true
        run: |
          echo "Condition is true!"
          echo "$env.PILOT_BRANCH_NAME"
          echo "${{ env.PILOT_BRANCH_NAME }}"
        if: ${{ contains(github.ref, PILOT_BRANCH_NAME) }}  # If condition is true

      - name: Run else condition
        run: |
          echo "Condition is false!"
        if: ${{ !contains(github.ref, 'main') }}  # Else condition
