name: Fourth Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version No'
        required: true

env:
  PATH: release/*
  PILOT_BRANCH_NAME: "release/${{ inputs.release_version }}-common-pilot"
  
jobs:
  if-condition:
    runs-on: ubuntu-latest
    steps:
      - name: Run task for main branch
        run: |
          echo "Running task for the main branch"
          echo "Input branch ${{ env.PILOT_BRANCH_NAME }} branch"
          echo "Path: ${{ env.PATH }}"

  else-condition:
    runs-on: ubuntu-latest
    steps:
      - name: Run task for non-main branch
        run: |
          echo "Running task for ${{ github.ref }} branch"
          echo "Input branch ${{ env.PILOT_BRANCH_NAME }} branch"
          echo "Path: ${{ env.PATH }}"
      
