name: Fourth Workflow Test

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release VersionNo'
        required: true
env:
  PILOT_BRANCH_NAME: "refs/heads/${{ inputs.release_version }}"

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Details
        run: |
          echo "Condition is true!"
          echo "${{ inputs.release_version }}"
          echo "${{ env.PILOT_BRANCH_NAME }}"
        
      - name: Run if condition is true
        run: |
          selected_branch_name="${{ github.ref }}"
          echo "$PILOT_BRANCH_NAME"
          if [[ $selected_branch_name == "$PILOT_BRANCH_NAME" && $selected_branch_name == *main* ]]; then
            echo "Running on main branch!"
          else
            echo "Running on other branch!"
            exit 1
          fi
          
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Running another gha script
        uses: ./..github/workflows/first-gha.yml
        with:
          APK_ARTIFACT_PATH: config/*
      
      - name: Final
        run: |
          echo "Job completed here"
