name: Second Workflow

on:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run if condition is true
        run: echo "Condition is true!"
        if: ${{ github.ref == 'refs/heads/test1' }}  # If condition is true

      - name: Run else condition
        run: echo "Condition is false!"
        if: ${{ github.ref == 'refs/heads/main' }}  # Else condition
