name: Take Input GHA

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub username'
        required: true
        default: 'exampleuser'
      environment:
        description: 'Deployment environment (e.g., production, staging)'
        required: true
        default: 'staging'

permissions:
  contents: read      # Read access to repository contents
  issues: write       # Write access to issues
  pull-requests: write
  workflow: write     # This allows you to trigger other workflows
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Display input values
        run: |
          echo "Username: ${{ github.event.inputs.username }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
        
      - name: Call next workflow with inputs
        run: |
          echo "Calling next workflow and send data"
          curl -X POST \
            -H "Authorization: Bearer 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" \
            -d '{"ref": "main", "inputs": {"username": "${{ github.event.inputs.username }}", "environment": "${{ github.event.inputs.environment }}"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/next-workflow.yml/dispatches
