name: Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: 'Your Name'
        required: true
        type: string
        default: Parth

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger second workflow with inputs
        uses: .github/workflows/workflow-dispatch@v1
        with:
          repository: user/repo-name
          workflow: next-workflow.yml
          ref: main
          inputs: |
            user_name: ${{ github.event.inputs.user_name }}
