name: First Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for second workflow'
        required: true
        type: string

jobs:
  generate_data:
    runs-on: ubuntu-latest
    steps:
      - name: Generate data and save to file
        run: |
          echo "Message from the first workflow: ${{ github.event.inputs.message }}" > message.txt

      - name: Upload message as artifact
        uses: actions/upload-artifact@v3
        with:
          name: message-artifact
          path: message.txt
