name: Third Workflow

on:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Testing branch name
        run: |
          if [[ github.ref =~ main ]]; then
            echo "Running on main branch!"
          else
            echo "Running on other branch!"
